Authentication/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    path('', include('allauth.urls')),

    # List of all available urls
    # url(r"^signup/$", views.signup, name="account_signup"),
    # url(r"^login/$", views.login, name="account_login"),
    # url(r"^logout/$", views.logout, name="account_logout"),
    # url(r"^password/change/$", views.password_change,
    #     name="account_change_password"),
    # url(r"^password/set/$", views.password_set, name="account_set_password"),
    # url(r"^inactive/$", views.account_inactive, name="account_inactive"),
    # # E-mail
    # url(r"^email/$", views.email, name="account_email"),
    # url(r"^confirm-email/$", views.email_verification_sent,
    #     name="account_email_verification_sent"),
    # url(r"^confirm-email/(?P<key>[-:\w]+)/$", views.confirm_email,
    #     name="account_confirm_email"),
    # # password reset
    # url(r"^password/reset/$", views.password_reset,
    #     name="account_reset_password"),
    # url(r"^password/reset/done/$", views.password_reset_done,
    #     name="account_reset_password_done"),
    # url(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
    #     views.password_reset_from_key,
    #     name="account_reset_password_from_key"),
    # url(r"^password/reset/key/done/$", views.password_reset_from_key_done,
    #     name="account_reset_password_from_key_done"),
]

HomeSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from Contact import views
from django.conf.urls.static import static

admin.sites.AdminSite.site_header = 'StackOverflow Clone Administration'
admin.sites.AdminSite.site_title = 'StackOverflow Clone Administration'
admin.sites.AdminSite.index_title = 'Ankit Administration'

urlpatterns = [
    url(r'^secretadmin/', admin.site.urls),
    path('',views.home,name='home'),
    path('contact/',views.contact,name='contact'),
    path('search/',views.search,name='search'),
    path('profile/',views.profile,name='profile'),
    path('users/',views.users,name='users'),

    #app urls
     path('blog/', include('blog.urls')),
     path('account/', include('Authentication.urls')),
     path('home/', include('StackoverflowClone.urls')),
    
]

handler404 = 'Contact.views.error_404_view' 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

StackoverflowClone/urls.py
from django.shortcuts import render
from django.urls import path  
from . import views

urlpatterns = [
    path('',views.homepage,name='homepage'),
    path('about/',views.about,name='about'),
    #urls
    
]

blog/urls.py
from django.urls import path, include
from .import views

app_name = 'blog'
#If you want to refer to any blog url you have to this else error
#{% url 'blog:blog' %},because I have set the app_name to 'blog'

urlpatterns = [
    path('',views.all_blog,name='blog'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

Contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.TextField(max_length=122)
    email = models.EmailField(max_length=122)
    phone = models.CharField(max_length=22,blank=True)
    desc = models.TextField(max_length=122)

    def __str__(self):
        return self.name

StackoverflowClone/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()


    def __str__(self):
        return self.title

Contact/forms.py
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
# from django import forms

# class CreateUserForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username', 'email', 'password1', 'password2'] 

Authentication/views.py
from django.shortcuts import render, redirect

# Create your views here.

def profilr(request):
    return render (request, 'Authentication/profile.html')

Contact/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User, auth
from django.http import HttpResponse
from .models import Contact
from blog.models import Blog
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import get_user_model
# Create your views here.

def users(request):
    User = get_user_model()
    users = User.objects.all()
    return render(request, 'Contact/users.html',{'users':users})

def home(request):
    return render(request, 'Contact/home.html')

def error_404_view(request, exception):
    return render(request, 'Contact/404.html')


@login_required
def profile(request):
    return render(request, 'Contact/profile.html')


def del_user(request, username):
    try:
        u = User.objects.get(username=username)
        u.delete()
        messages.success(request, "The user is deleted")

    except User.DoesNotExist:
        messages.error(request, "User doesnot exist")
        return render(request, 'Contact/home.html')

    except Exception as e:
        return render(request, 'Contact.html', {'err': e.message})

    return render(request, 'Contact/home.html')


@login_required
def search(request):
    query = request.GET['query']
    if len(query) > 15:
        messages.warning(
            request, 'Search query must be a maximum of 15 characterss')
        blogs = Blog.objects.none()
    if len(query) < 5:
        messages.warning(request, 'Search query must be minimum 5 characters')
        blogs = Blog.objects.none()

    else:
        blogstittle = Blog.objects.filter(title__icontains=query)
        blogscontent = Blog.objects.filter(description__icontains=query)
        blogs = blogstittle.union(blogscontent)

    if blogs.count() == 0:
        messages.warning(
            request, 'No search results found,Kindly refine your query')

    params = {'blogs': blogs, 'query': query}
    return render(request, 'Contact/search.html', params)


@login_required
def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        desc = request.POST.get('desc')

        if len(desc) < 20:
            messages.error(
                request, 'The message should contain atleast 20 characters!')
        else:
            contact = Contact(name=name, email=email, phone=phone, desc=desc)
            contact.save()
            messages.success(
                request, 'Your message has been successfully sent!')
            return redirect('contact')
    return render(request, 'Contact/contact.html')

StackoverflowClone/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.

def homepage(request):
    return render (request, 'StackoverflowClone/home.html')


def about(request):
    return render (request, 'StackoverflowClone/about.html')

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog

# Create your views here.
def all_blog(request):
    blogs = Blog.objects.order_by('-date')
    return render (request,'blog/all_blog.html',{'blogs':blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html',{'blog':blog})

Contact/templates/Contact/contact.html
{% extends 'StackoverflowClone/base.html' %}

{% block content %}
    <style>
    h2 {
      text-align: center;
    }
    hr {
      border-width: 2px;
    }
  </style>
</head>
  <form method="POST">
    {% csrf_token %}
    <div class="container ">
      <h2>Contact Us</h2><hr>
      <!-- <div class="container"> -->
        <div class="form-group">
          <label for="exampleFormControlInput1">Email address *</label>
        <input name="email" type="email" class="form-control" id="exampleFormControlInput1"
          placeholder="name@example.com" required>
      </div>
      <div class="form-group">
        <label for="exampleFormControlSelect1">Your Name *</label>
        <input name="name" type="text" multiple class="form-control" placeholder="Your Name" required>
      </div>
      <div class="form-group">
        <div class="form-group">
          <label for="phone">Enter a phone number (optional)</label><br>
          <input name="phone" type="tel" id="phone" name="phone" multiple class="form-control"
            placeholder="Enter Your Phone Number In the format given below " pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}">
          <small>Format: 012-345-6789</small><br>
          <small>The phone feature is only available in India</small>
        </div>
        <div class="form-group">
          <label for="exampleFormControlTextarea1">Describe Your Issue *</label>
          <textarea name="desc" class="form-control" id="exampleFormControlTextarea1" rows="3"
            placeholder="Please be detailed with your issue" ></textarea><br>
          <input class="btn btn-primary" type="submit">
          <br>
          <hr>
        </div>
      </div>
    </div>
  </form>
{% endblock content %}

Contact/templates/Contact/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="icon" type="image/png"  href="{% static 'StackoverflowClone/logo.png' %}">
  <title>Welcome Page</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
  <style>
    .collapsible {
      background-color: #777;
      color: white;
      cursor: pointer;
      padding: 18px;
      width: 100%;
      border: none;
      text-align: left;
      outline: none;
      font-size: 15px;
    }
    
    .active, .collapsible:hover {
      background-color: #555;
    }
    
    .collapsible:after {
      content: '\002B';
      color:#777;
      font-weight: bold;
      float: right;
      margin-left: 5px;
    }
    
    .active:after {
      content: "\2212";
    }
    
    .content {
      padding: 0 18px;
      max-height: 0;
      overflow: hidden;
      transition: max-height 0.2s ease-out;
      background-color: #f1f1f1;
    }
    hr {
      border-width: 2px;
      color: red;
    }

    * {
      box-sizing: border-box;
    }

    .columns {
      float: left;
      width: 33.3%;
      padding: 8px;
    }

    .price {
      list-style-type: none;
      border: 1px solid #eee;
      margin: 0;
      padding: 0;
      -webkit-transition: 0.3s;
      transition: 0.3s;
    }

    .price:hover {
      box-shadow: 0 8px 12px 0 rgba(0, 0, 0, 0.2)
    }

    .price .header {
      background-color: #111;
      color: white;
      font-size: 25px;
    }

    .price li {
      border-bottom: 1px solid #eee;
      padding: 20px;
      text-align: center;
    }

    .price .grey {
      background-color: #eee;
      font-size: 20px;
    }

    .button {
      background-color: #4CAF50;
      border: none;
      color: white;
      padding: 10px 25px;
      text-align: center;
      text-decoration: none;
      font-size: 18px;
    }

    @media only screen and (max-width: 600px) {
      .columns {
        width: 100%;
      }
    }

    .columns {
      width: 100%;
    }

    hr {
      border-width: 2px;
    }

    .i1,
    .i2 {
      color: rgb(20, 169, 238);
    }

    .footer {
      padding: 60px 0;
      width: 100%;
      background: #3B008D;
      color: #fff;

    }

    .footer-title {
      position: relative;
      color: #fff;
      font-size: 24px;
      font-weight: 600;
      margin-top: 5px;
      margin-bottom: 20px;
      border-bottom: 1px solid #4e4e4e;
    }
  </style>

</head>

<body>

  <div class="jumbotron text-center ">
    <h1>Stack Overflow Clone</h1> <br>
    <p><strong><i>Questions are everywhere, answers are on StackOverflow Clone</i></strong></p>
    <a class="btn btn-outline-primary my-3" href="#fordevelopers">For Developers</a>
    <a class="btn btn-outline-danger mx-4" href="#Q&A">Most asked questions</a>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <h3>Learn More!</h3>
        <p>Education gives us a knowledge of the world around us and changes it into something better. It develops in us
          a perspective of looking at life</p>
        <p>Education is the passport to the future, for tomorrow belongs to those who prepare for it today....</p>
      </div>
      <div class="col-sm-4">
        <h3>Some great quotes</h3>
        <p><i>Live as if you were to die tomorrow. Learn as if you were to live forever</i></p>
        <p><i>Education is what remains after one has forgotten what one has learned in school</i></p>
        <br>
      </div>
      <div class="col-sm-4">
        <h3>Get Motivated</h3>
        <p>The roots of education are bitter, but the fruit is sweet</p>
        <p>Strive for progress, not perfection</p>
      </div>
    </div>
    <br>
  </div>
  </div>
  <div class="container text-center">
    <form action="{% url 'homepage' %}">
      <button class="btn btn-primary " type="submit">Get started</button>
    </form>
  </div>

  <div class="container text-center">
    <hr>
    <br>
    <h2 id="fordevelopers">For Developers, by Developers</h2><br>
    <h4>
      <p>
        Stack Overflow Clone is an open community for anyone who codes or want help.
        We help you get answers to your  coding questions, share knowledge with
        others worldwide and get help when you are stuck , get ready to ace your next dream job
      </p><br>
    </h4>
    <hr>
  </div>
  </div>
  <br>
  <br>

  <div class="container">
    <h2 class="text-center" id="Q&A">Frequently asked questions</h2>
    <br>
  <button type="button" class="collapsible">Why do I need to Signup?</button>
<div class="content">
  <p>Signing up gives you the advantage to posts your questions in the site, if you are lucky you can get help from
    others, in simple words signup gives you the power to ask your own questions, and help others </p>
</div>
  <button type="button" class="collapsible">Why do I need to Login?</button>
  <div class="content">
    <p>If You already have a account that's great, sometimes you need to logout for any purpose then to enter again in our Website, you need to login!</p>
  </div>
    <button type="button" class="collapsible">Is our Website free to use?</button>
    <div class="content">
      <p> Our website is free to use and will always be free for everyone to use. We believe in helping others rather than earning money, you don't need a reason to help people :) </p>
    </div>
      <button type="button" class="collapsible">What's the motive of this platform?</button>
      <div class="content">
        <p>In this modern world we can't stay alive without each other's help. We all get stuck at any point of time in our life. Luckily we have our parents to support us, but how long they can support?
          So introducing our new platform which will help people from worldwide to discuss their problems with other's and get their problems solved, if you are lucky you can get help from other's or you can help other's to make their day nice!
          There is a common saying "If you help someone you may not have changed the world, but the help can change the world for that person!"
          </p>
      </div>
        
</div>
  </div>
  </div>
  <br><br>
  <div class="container text-center">
    <p class="mt-2"><b>Our Website is free to use, what are you waiting for?</b></p><br>
    <p>Have 99 problems in your life? Don't make it 100, Create a account on our website and solve them all</p><br>
    <ul class="price">
      <li class="header" style="background-color:#4CAF50">Free</li>
      <li class="grey"><del class="mr-3">$ 100 / year </del><del class="mr-3">$ 200 / year </del><br>&#10004; $ 0 / year</li>
      <li>&#10003; Get your questions solved</li>
      <li>&#10003; Ask Unlimited questions</li>
      <li>&#10003; 24x7 Support</li>
      <li>&#10003; Free for lifetime</li>
      <li class="grey"><a href="{% url 'homepage' %}" class="button">Let's Go!</a></li>
    </ul>
  </div>
  </div><br><br>
  <br>
  <script>
    var acc = document.getElementsByClassName("accordion");
    var i;

    for (i = 0; i < acc.length; i++) {
      acc[i].addEventListener("click", function () {
        this.classList.toggle("active");
        var panel = this.nextElementSibling;
        if (panel.style.maxHeight) {
          panel.style.maxHeight = null;
        } else {
          panel.style.maxHeight = panel.scrollHeight + "px";
        }
      });
    }
    var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.maxHeight){
      content.style.maxHeight = null;
    } else {
      content.style.maxHeight = content.scrollHeight + "px";
    } 
  });
}
  </script>
  <footer class="page-footer bg-dark">

    <div class="bg-success">
      <div class="container">
        <div class="row py-4 d-flex align-items-cemter">
          <div class="col-md-12 text-center">
            <a href="https://www.facebook.com/ankit.mitra.9028/ " target="_blank"><i
                class="fab fa-facebook-f mr-4 "></i></a>
            <a href="https://www.instagram.com/ankit_coder1/" target="_blank"><i class="fab fa-instagram mr-4 "></i></a>
            <a href="https://www.linkedin.com/in/ankit-mitra-6333ba1aa/" target="_blank"><i
                class="fab fa-linkedin-in mr-4 "></i></a>
            <a href="mailto:ankitmitra486@gmail.com" target="_blank"><i class="far fa-envelope-open mr-4"></i></a>
            <a href="http://ankitmitra.pythonanywhere.com/" target="_blank"><i
                class="fas fa-external-link-alt mr-4"></i></a>
          </div>
        </div>
      </div>
    </div>

    <div class=" container text-center text-md-left mt-5 ">
      <div class="row">
        <div class="col-md-3 mb-4 mx-auto">
          <h6 class="text-uppercase font-weight-bold">Stack Overflow Clone</h6>
          <hr class="bg-success mb-4 mt-0 mx-auto d-inline-block" style="width: 125px; height: 2px;">
          <p class="mt-2"> Stack Overflow Clone is an open community for anyone who codes or want help.
            We help you get answers to your questions, share knowledge with
            others worldwide and get help when you are stuck , get ready to ace your next dream job.</p>
        </div>

        <div class="col-md-3 mb-4 mx-auto">
          <h6 class="text-uppercase font-weight-bold">Give a look at</h6>
          <hr class="bg-success mb-4 mt-0 mx-auto d-inline-block" style="width: 125px; height: 2px;">
          <ul class="list unstyled">
            <li class="my-2"><a href="https://github.com/AnkitMItraOfficial/StackOverflowClone" target="blank">Github Project</a></li>
            <li class="my-2"><a href="{% url 'about' %}">About Us</a></li>
            <li class="my-2"><a href="#">Terms and Policy</a></li>
            <li class="my-2"><a href="#">Cookies</a></li>
          </ul>
        </div>
        <div class="col-md-3 mb-4 mx-auto">
          <h6 class="text-uppercase font-weight-bold">Explore</h6>
          <hr class="bg-success mb-4 mt-0 mx-auto d-inline-block" style="width: 110px; height: 2px;">
          <ul class="list unstyled">
            <li class="my-2"><a href="{% url 'blog:blog' %}">Blog</a></li>
            <li class="my-2"><a href="{% url 'contact' %}">Contact Us</a></li>
            <li class="my-2"><a href="#">Donate Us &#10084;</a></li>
            <li class="my-2"><a href="#">Request a Feature</a></li>
          </ul>
        </div>
        <div class="col-md-3 mb-4 mx-auto">
          <h6 class="text-uppercase font-weight-bold">Contacts</h6>
          <hr class="bg-success mb-4 mt-0 mx-auto d-inline-block" style="width: 110px; height: 2px;">

          <ul class="list unstyled">
            <li class="my-2"><i class="fas fa-home"></i> India, West-Bengal, Howrah</li>
            <li class="my-2"><i class="fas fa-phone"></i> <a href="tel:6291434319">Call +91 6291434319</a></li>
            <li class="my-2"><i class="fas fa-envelope"></i><a
                href="mailto:ankitmitra486@gmail.com"> ankitmitra486@gmail.com </a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright text-center  py-2">
      <p>&copy; All Rights Reserverd 2020<br>
        <a href="#">Stack Overflow Clone</a>
      </p>
    </div>
  </footer>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js">
  </script>
  <script type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
  </div>
  </div>
  </div>
</body>

</html>

Contact/templates/Contact/profile.html
{% extends "StackoverflowClone/base.html" %}
{% load crispy_forms_tags %}

{% load i18n %}
{% block content %}
<title>Your Profile</title>

<div class="alert alert-success alert-dismissible fade show" role="alert">
  <b>Feel free to update your profile {{ user.username }} </b>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<br><br>
<div class="container text-center">
     <div class="row">
        <div class="col-4">
          <div class="list-group" id="list-tab" role="tablist">
            <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="home">Username</a>
            <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-email" role="tab" aria-controls="profile">Email</a>
            <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-change" role="tab" aria-controls="messages">Change Password</a>
            <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-forgot" role="tab" aria-controls="settings">Forget Password</a>
            <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-feature" role="tab" aria-controls="settings">Request a Feature</a>
          </div>
        </div>
        <div class="col-8">
          <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">
                <h1>Username - {{ user.username }}</h1>
                <br>
                <h4>Your account was created on -- {{ user.date_joined }}</h4><br>
                <a class="btn btn-danger"  href="#" >Delete ccount</a></div>
            </p>
            <hr>
            <div class="tab-pane fade" id="list-email" role="tabpanel" aria-labelledby="list-email-list">
                <h3>Your email address is - <br>{{ user.email }}</h3><br>
                <a href="{% url 'account_email' %}" class="btn btn-primary">Change/Update email</a>

            </div>
            <div class="tab-pane fade" id="list-change" role="tabpanel" aria-labelledby="list-change-list">
                <h3>Changing Password frequently is a good way to secure your account</h3><br>
                <a href="{% url 'account_change_password' %}" class="btn btn-success" >{% trans "Change Password" %}</a>
            </div>
            <div class="tab-pane fade" id="list-forgot" role="tabpanel" aria-labelledby="list-forgot-list">
                <h4>Forgot Your Password? Don't worry! We have got your back!</h4><br>
                <a href="{% url 'account_reset_password' %}" class="btn btn-danger" >{% trans "Forgot Password" %}</a>
            </div>
                <div class="tab-pane fade" id="list-feature" role="tabpanel" aria-labelledby="list-feature-list">
                  <h3>Not Satisfied &#8253;</h3><br>
                  <h4>Request a feature here</h4><br>
                  <a href="{% url 'contact' %}" class="btn btn-success" >{% trans "Contact Us" %}</a>
              </div>
          </div>
        </div>
      </div>
      </div>
{% endblock content %}

Contact/templates/Contact/search.html
{% extends "StackoverflowClone/base.html" %}

{% block title %}Search results{% endblock title %}
{% block content %}
<br>
<div class="container">
  <h3>Search results:</h3>
  {% if blogs|length < 1 %}
  <p>No search Results found</p>

  Your search -  <kbd>{{ query }}</kbd>  - did not match any documents.<br>
<br>
Suggestions:
<ul>
<li>Make sure that all words are spelled correctly</li>
<li>Try different keywords.</li>
<li>Try more general keywords.</li>
<li>Try fewer keywords.</li>
</ul>
  {% endif %}
  {% for blog in blogs %}
  <div class="row justify-content-center my-3">
    <div class="col-md-10">
      <a href="{% url 'blog:detail' blog.id %}">
        <!--This creates the clickable option on the blog title-->
        <h2>{{ blog.title }}</h2>
      </a>
      <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
      <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
    </div>
  </div>
  {% endfor %}

  {% endblock %}

Contact/templates/Contact/users.html
{% extends "StackoverflowClone/base.html" %}

<h2>This are all Users</h2>

<!-- {% for user in users %}

{{ user }}

{% endfor %} -->
{% block content %}
{% endblock content %}

blog/templates/blog/all_blog.html
{% extends "StackoverflowClone/base.html" %}

{% load static %}

{% block content %}
<style>
  h2 {
    color: rgb(19, 168, 255);
  }
</style>
<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>
<!--This is the line to count the blogs ,{{ blogs.count|pluralize }} this code sets the blog/blogs and this {{ blogs.count }} counts  the blogs/blog-->
<h3 class="text-center mb-5">Ankit Mitra has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>

{% for blog in blogs %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
      <h2>{{ blog.title }}</h2>
    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4><br>
    <a  class="btn btn-outline-danger" href="{% url 'blog:detail' blog.id %}">Read More</a>
  </div>
</div>
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'StackoverflowClone/base.html' %}

{% load static %}

{% block content %}
<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>
<div class="container text-center">
    <h5>{{ blog.description|safe }}</h5>
</div>
<br>
<hr>
<div class="container text-center"><a class="btn btn-danger" href="{% url 'homepage' %}">Home</a>
</div>
{% endblock %}